FROM golang:1.25.1

WORKDIR /app
# Set Go cache
ENV GOCACHE=/tmp/.cache
RUN mkdir -p $GOCACHE


# Install Nancy 
RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.52/nancy-v1.0.52-linux-amd64 -O nancy && \
    chmod +x nancy && mv nancy /usr/local/bin/nancy 

# Install Staticcheck
RUN go install golang.org/x/lint/golint@latest


# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy project files
COPY . .
